listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10 && asusctl aura power-tuf --keyboard --awake false
    on-resume = brightnessctl -r && asusctl aura power-tuf --keyboard --awake true
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch 'hl.dsp.dpms { action = "disable" }'
    on-resume = hyprctl dispatch 'hl.dsp.dpms { action = "enable" }' && brightnessctl -r
}

listener {
    timeout = 3000
    on-timeout = systemctl suspense
}
